title = "Ximena Reyna"
baseURL = "https://Ximena-Reyna.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "arduino"
enableGitInfo = false

[params]
address = "Canton, MI"
email = ""
favicon = "/img/xreyna_24x24.ico"
firstName = "Alejandra Ximena"
lastName = "Reyna Altamirano"
phone = ""
profileImage = "/img/xreyna.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showCoursework = true
showPublications = false
showQr = false
showSkills = true


# [[params.handles]]
# link = "https://www.linkedin.com/in/joseph-C-starr/"
# name = "LinkedIn"

# [[params.handles]]
# link = "https://github.com/Joecstarr/"
# name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"